version: "2.4"

services:
  app:
    build:
      args:
        NODE_ENV: development
        INSTALL_XDEBUG: '$XDEBUG'
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: {{APP_NAME}}-app
    env_file:
      - .env
    image: clevyr/{{APP_NAME}}/app
    restart: unless-stopped
    volumes:
      - .:/app:cached

  worker:
    build:
      args:
        NODE_ENV: development
        INSTALL_XDEBUG: '$XDEBUG'
      context: .
      dockerfile: docker/app/Dockerfile
    command: ["s6-svscan", "/etc/s6/worker"]
    container_name: {{APP_NAME}}-worker
    env_file:
      - .env
    image: clevyr/{{APP_NAME}}/app
    restart: unless-stopped
    volumes:
      - .:/app:cached

  proxy:
    container_name: {{APP_NAME}}-proxy
    environment:
      REVERSE_PROXY: "true"
      APP_HOST: "app"
      APP_PORT: "80"
    depends_on:
      - app
    image: clevyr/caddy
    ports:
      - 80:80
    restart: unless-stopped

  database:
    container_name: {{APP_NAME}}-database
    environment:
      POSTGRES_USER: "$DB_USERNAME"
      POSTGRES_PASSWORD: "$DB_PASSWORD"
      POSTGRES_DB: "$DB_DATABASE"
    image: postgres:11.1-alpine
    ports:
      - 127.0.0.1:5432:5432
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: unless-stopped

  hot:
    build: docker/hot
    container_name: {{APP_NAME}}-hot
    env_file:
        - .env
    image: clevyr/{{APP_NAME}}/hot-reloader
    restart: unless-stopped
    volumes:
      - .:/app:cached

volumes:
  database:
