version: 2.1
jobs:
  build:
    docker:
      - image: clevyr/circleci-ecr-builder:1.0.1
    environment:
      APP_NAME: {{APP_NAME}}

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build App
          command: docker build -t 396720968759.dkr.ecr.us-east-2.amazonaws.com/$APP_NAME/app -f docker/app/Dockerfile.prod .
      - run:
          name: Login to ECR
          command: eval $(aws ecr get-login --region us-east-2 --no-include-email)
      - run:
          name: Push App
          command: docker push 396720968759.dkr.ecr.us-east-2.amazonaws.com/$APP_NAME/app:latest
      - run:
          name: Deploy App
          command: aws ecs --region us-east-2 update-service --cluster teamclinics --service app --force-new-deployment
      - run:
          name: Deploy Caddy
          command: aws ecs --region us-east-2 update-service --cluster teamclinics --service caddy --force-new-deployment

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
